insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (1, 'kills', 'Executioner', 'Most kills');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (2, 'kills_2', 'Fragger', 'Kills');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (3, 'damage', 'Pain Train', 'Most damage');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (4, 'damage_2', 'Bruiser', 'Damage');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (5, 'adr', 'Carry', 'Highest ADR');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (6, 'adr_2', 'Workhorse', 'ADR');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (7, 'mvps', 'Most Valuable MVP', 'Most MVPs');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (8, 'mvps_2', 'Valuable Player', 'MVPs');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (9, 'assists', 'Tenderizer', 'Most assists');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (10, 'assists_2', 'Assistant', 'Assists');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (11, 'hsp', 'Bullseye', 'Highest headshot percentage');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (12, 'hsp_2', 'Good Shot', 'Headshot percentage');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (13, '3k', 'Trifecta', 'Most 3-kills');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (14, '3k_2', 'Triple', '3-kills');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (15, '4k', 'Quad Killer', 'Most 4-kills');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (16, '4k_2', 'Quad', '4-kills');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (17, '5k', 'Ace of Aces', 'Most aces');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (18, '5k_2', 'Ace in the Hole', 'Aces');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (19, 'headshotkills', 'Assassin', 'Most headshot kills');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (20, 'headshotkills_2', 'Headhunter', 'Headshot kills');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (21, 'killreward', 'Bounty Hunter', 'Highest kill reward earnings');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (22, 'killreward_2', 'Mercenary', 'Kill reward earnings');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (23, 'utilitydamage', 'Demo Master', 'Most utility damage');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (24, 'utilitydamage_2', 'Demo Expert', 'Utility damage');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (25, 'enemiesflashed', 'Flash', 'Most enemies flashed');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (26, 'enemiesflashed_2', 'Support', 'Enemies flashed');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (27, 'objective', 'Task Master', 'Most objectives');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (28, 'objective_2', 'Tasker', 'Objectives');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (29, 'worth', 'Spartan', 'Equipment Value');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (30, 'worth_2', 'Penny-wise', 'Equipment Value');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (31, 'score', 'Score Master', 'Highest score');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (32, 'score_2', 'Scorer', 'Score');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (33, 'livetime', 'Ancient One', 'Most time alive');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (34, 'livetime_2', 'Old Timer', 'Time alive');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (35, 'deaths', 'Click Bait', 'Most deaths');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (36, 'deaths_2', 'Fearless', 'Deaths');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (37, 'nopurchasewins', 'Scavenger', 'Most round wins with no purchase');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (38, 'nopurchasewins_2', 'Frugalist', 'Round wins with no purchase');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (39, 'clutchkills', 'Clutch King', 'Most clutch kills');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (40, 'clutchkills_2', 'Cleanup', 'Clutch kills');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (41, 'loudest', 'Loudfoot', 'Most audible footsteps');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (42, 'loudest_2', 'Confident', 'Audible footsteps');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (43, 'quietest', 'Ninja', 'Fewest audible footsteps');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (44, 'quietest_2', 'Stalker', 'Audible footsteps');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (45, 'pistolkills', 'Gunslinger', 'Most pistol kills');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (46, 'pistolkills_2', 'Sidearm', 'Pistol kills');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (47, 'firstkills', 'Entry Fragger', 'Most first kills');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (48, 'firstkills_2', 'Quick Draw', 'First kills');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (49, 'sniperkills', 'Sharpshooter', 'Most sniper kills');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (50, 'sniperkills_2', 'Sniper', 'Sniper kills');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (51, 'roundssurvived', 'Die Hard', 'Most rounds survived');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (52, 'roundssurvived_2', 'Survivalist', 'Rounds survived');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (53, 'chickenskilled', 'Colonel', 'Most chickens massacred');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (54, 'chickenskilled_2', 'Master Chef', 'Chickens massacred');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (55, 'killswhileblind', 'Blind Hero', 'Most kills while blind');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (56, 'killswhileblind_2', 'Trick Shot', 'Kills while blind');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (57, 'bombcarrierkills', 'Wall', 'Most bomb carrier kills');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (58, 'bombcarrierkills_2', 'Interference', 'Bomb carrier kills');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (59, 'burndamage', 'Fire Starter', 'Most burn damage');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (60, 'burndamage_2', 'Toaster', 'Burn damage');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (61, 'cashspent', 'Big Spender', 'Most money spent');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (62, 'cashspent_2', 'Spender', 'Money spent');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (63, 'uniqueweaponkills', 'Weapons Master', 'Most unique weapon kills');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (64, 'uniqueweaponkills_2', 'Weapons Trainer', 'Unique weapon kills');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (65, 'dinks', 'Dink Master', 'Most dinks');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (66, 'dinks_2', 'Barber', 'Dinks');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (67, 'gimme_01', 'Moral Support', '');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (68, 'gimme_02', 'Participant', '');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (69, 'gimme_03', 'Reservist', '');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (70, 'gimme_04', 'Backup Plan', '');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (71, 'gimme_05', 'Rearguard', '');
insert into accolade_pretty_names (id, accolade_name, pretty_name, description) values (72, 'gimme_06', 'Armchair General', '');
