// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Accolade struct {
	ID            int64
	PlayerID      pgtype.Int8
	MatchID       pgtype.Int8
	AccoladeTime  pgtype.Time
	AccoladeDate  pgtype.Date
	AccoladeName  string
	AccoladeValue string
	AccoladePos   int32
	AccoladeScore string
}

type AccoladePrettyName struct {
	ID           int64
	AccoladeName string
	PrettyName   string
	Description  string
}

type Attack struct {
	ID                int64
	AttackerID        pgtype.Int8
	AttackedID        pgtype.Int8
	RoundID           pgtype.Int8
	AttackTime        pgtype.Time
	AttackDate        pgtype.Date
	AttackerTeamID    pgtype.Int8
	AttackedTeamID    pgtype.Int8
	AttackerPositionX int32
	AttackerPositionY int32
	AttackerPositionZ int32
	AttackedPositionX int32
	AttackedPositionY int32
	AttackedPositionZ int32
	AttackerWeaponID  pgtype.Int8
	Damage            int32
	DamageArmor       int32
	Health            int32
	Armor             int32
	HitGroupID        pgtype.Int8
}

type Blinded struct {
	ID              int64
	BlindedID       pgtype.Int8
	BlindedByID     pgtype.Int8
	RoundID         pgtype.Int8
	BlindedTime     pgtype.Time
	BlindedDate     pgtype.Date
	BlindedTeamID   pgtype.Int8
	BlindedByTeamID pgtype.Int8
	BlindedFor      string
	Entindex        int32
}

type Event struct {
	ID   int64
	Name string
}

type GameType struct {
	ID   int64
	Name string
}

type HitGroup struct {
	ID   int64
	Name string
}

type Item struct {
	ID   int64
	Name string
}

type ItemAction struct {
	ID   int64
	Name string
}

type ItemInteraction struct {
	ID              int64
	PlayerID        pgtype.Int8
	TeamID          pgtype.Int8
	RoundID         pgtype.Int8
	ItemID          pgtype.Int8
	ItemAction      pgtype.Int8
	InteractionTime pgtype.Time
	InteractionDate pgtype.Date
}

type Kill struct {
	ID              int64
	KillerID        pgtype.Int8
	KilledID        pgtype.Int8
	RoundID         pgtype.Int8
	KillTime        pgtype.Time
	KillDate        pgtype.Date
	KillerTeamID    pgtype.Int8
	KilledTeamID    pgtype.Int8
	KillerPositionX int32
	KillerPositionY int32
	KillerPositionZ int32
	KilledPositionX int32
	KilledPositionY int32
	KilledPositionZ int32
	KillerWeaponID  pgtype.Int8
	SpecialID       pgtype.Int8
}

type KillsAssisted struct {
	ID           int64
	KillerID     pgtype.Int8
	KilledID     pgtype.Int8
	RoundID      pgtype.Int8
	KillTime     pgtype.Time
	KillDate     pgtype.Date
	KillerTeamID pgtype.Int8
	KilledTeamID pgtype.Int8
}

type KillsOther struct {
	ID              int64
	KillerID        pgtype.Int8
	KilledOtherID   pgtype.Int8
	RoundID         pgtype.Int8
	KillTime        pgtype.Time
	KillDate        pgtype.Date
	KillerTeamID    pgtype.Int8
	KillerPositionX int32
	KillerPositionY int32
	KillerPositionZ int32
	KilledPositionX int32
	KilledPositionY int32
	KilledPositionZ int32
	KillerWeaponID  pgtype.Int8
}

type Map struct {
	ID   int64
	Name string
}

type Match struct {
	ID         int64
	StartDate  pgtype.Date
	StartTime  pgtype.Time
	EndDate    pgtype.Date
	EndTime    pgtype.Time
	MapID      pgtype.Int8
	ScoreCt    int32
	ScoreT     int32
	GameTypeID pgtype.Int8
}

type MoneyChange struct {
	ID         int64
	PlayerID   pgtype.Int8
	TeamID     pgtype.Int8
	RoundID    pgtype.Int8
	ItemID     pgtype.Int8
	NewTotal   int32
	ChangeTime pgtype.Time
	ChangeDate pgtype.Date
}

type OtherKill struct {
	ID   int64
	Name string
}

type Player struct {
	ID          int64
	SteamUserID pgtype.Int8
	Name        string
	Bot         pgtype.Bool
}

type PlayerSuicide struct {
	ID              int64
	PlayerID        pgtype.Int8
	TeamID          pgtype.Int8
	RoundID         pgtype.Int8
	WithItemID      pgtype.Int8
	PlayerPositionX int32
	PlayerPositionY int32
	PlayerPositionZ int32
	SuicideTime     pgtype.Time
	SuicideDate     pgtype.Date
}

type Round struct {
	ID           int64
	StartDate    pgtype.Date
	StartTime    pgtype.Time
	EndDate      pgtype.Date
	EndTime      pgtype.Time
	MatchID      pgtype.Int8
	WinnerTeamID pgtype.Int8
}

type RoundTeam struct {
	ID       int64
	PlayerID pgtype.Int8
	TeamID   pgtype.Int8
	RoundID  pgtype.Int8
}

type SpecialKill struct {
	ID   int64
	Name string
}

type SteamUser struct {
	ID               int64
	SteamID          string
	SteamCommunityID int64
}

type Team struct {
	ID   int64
	Name string
}

type TeamSwitch struct {
	ID         int64
	PlayerID   pgtype.Int8
	FromTeamID pgtype.Int8
	ToTeamID   pgtype.Int8
	SwitchDate pgtype.Date
	SwitchTime pgtype.Time
	RoundID    pgtype.Int8
}

type Threw struct {
	ID        int64
	PlayerID  pgtype.Int8
	TeamID    pgtype.Int8
	RoundID   pgtype.Int8
	ThrewTime pgtype.Time
	ThrewDate pgtype.Date
	PositionX int32
	PositionY int32
	PositionZ int32
	WeaponID  pgtype.Int8
	Entindex  int32
}

type TriggeredEvent struct {
	ID        int64
	PlayerID  pgtype.Int8
	TeamID    pgtype.Int8
	RoundID   pgtype.Int8
	EventID   pgtype.Int8
	EventTime pgtype.Time
	EventDate pgtype.Date
	Bombsite  string
}

type Weapon struct {
	ID   int64
	Name string
}
